env:
    - GHCVER=7.8.3

before_install:
    - sudo add-apt-repository -y ppa:hvr/ghc
    - sudo add-apt-repository -y ppa:chris-lea/node.js
    - sudo apt-get update -qq
    - sudo apt-get build-dep ghc
    - sudo apt-get install nodejs cabal-install-1.18 ghc-$GHCVER
    - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
    - cabal-1.18 update
    - cabal-1.18 install alex happy
    - git clone https://github.com/ghcjs/cabal.git
    - cd cabal
    - git checkout ghcjs
    - cabal-1.18 install ./Cabal ./cabal-install
    - cabal --version
    - cd ..
    - git clone https://github.com/ghcjs/ghcjs-prim.git
    - git clone https://github.com/ghcjs/haddock-internal.git
    - cabal install ./ghcjs-prim ./haddock-internal
    - cabal install --enable-tests --enable-benchmarks
    - ghcjs --version
    - ghcjs-boot --version
    - ghcjs-boot --dev --with-node nodejs
    - cabal install -j2 --ghcjs random QuickCheck
    - ghcjs-pkg list

script:
    - ./dist/build/test/test -j 2 -t ghc -t conc -t integer -t ffi -t profiling

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
