language: haskell

before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install darcs libgmp3-dev libgmp3c2 freeglut3 freeglut3-dev
    - wget http://www.haskell.org/ghc/dist/7.6.1/ghc-7.6.1-i386-unknown-linux.tar.bz2
    - tar -xjf ghc-7.6.1-i386-unknown-linux.tar.bz2
    - cd ghc-7.6.1
    - ./configure --prefix=$HOME/ghc-7.6.1
    - make install
    - export PATH=$HOME/ghc-7.6.1/bin:$PATH
    - cd ..
    - rm -rf ghc-7.6.1
    - rm ghc-7.6.1-i386-unknown-linux.tar.bz2

install:
    - cabal install mega-sdist hspec cabal-meta cabal-src
    - cabal-meta install --force-reinstalls
    - rm -rf dist vendor

script:
   - wget http://www.haskell.org/ghc/dist/7.6.1/ghc-7.6.1-src.tar.bz2
   - tar -xjf ghc-7.6.1-src.tar.bz2 
   - rm ghc-7.6.1-src.tar.bz2
   - cd ghc-7.6.1
   - cp mk/build.mk.sample mk/build.mk
   - perl boot
   - ./configure --prefix=$HOME/ghc-7.6.1
   - cd ghc
   - make stage=1
   - cd ../libraries
   - make
   - cd ..
   - ghcjs-boot

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
  email: true

