env:
    - GHCVER=7.8.2

before_install:
    - sudo add-apt-repository -y ppa:hvr/ghc
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install darcs libgmp3-dev libgmp3c2 freeglut3 freeglut3-dev
    - sudo apt-get build-dep ghc
    - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
    - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
    - cabal-1.18 update
    - cabal-1.18 install alex happy
    - git clone https://github.com/ghcjs/cabal.git
    - cd cabal
    - git checkout ghcjs
    - cabal-1.18 install ./Cabal ./cabal-install
    - cabal --version
    - cd ..
    - cabal install --enable-executable-dynamic --enable-tests --enable-benchmarks
    - ghcjs --version
    - ghcjs-boot --version
    - ghcjs-boot --init
    - cabal install -j2 --ghcjs stm random syb transformers text parallel QuickCheck old-time vector
    - ghcjs-pkg list

script:
    - ./dist/build/test/test -j 2 -t ghc -t conc -t integer -t ffi

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
